# Sử dụng image chính thức của Maven để build ứng dụng
FROM maven:3.8.1-openjdk-11 AS build
COPY src /home/app/src
COPY pom.xml /home/app
RUN mvn -f /home/app/pom.xml clean package -DskipTests

#  Lần cuói :)) haha Kiên trì lên bạn ơi
# Sử dụng image chính thức của OpenJDK để chạy ứng dụng
FROM openjdk:11-jre-slim
COPY --from=build /home/app/target/project-service-0.0.1-SNAPSHOT.jar /usr/local/lib/project-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/usr/local/lib/project-service-0.0.1-SNAPSHOT.jar"]
# Chỗ your-application. thay bằng gì bạn ơi