
server:
  port: 8080
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: TaskService
          uri: http://localhost:9001
          predicates:
            - Path=/api/task/**
        - id: ProjectService
          uri: http://localhost:9002
          predicates:
            - Path=/api/project/**
        - id: UserService
          uri: http://localhost:9003
          predicates:
            - Path=/api/user/**

  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8086/eureka
